import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { PwaInstallButtonWrapper } from "@/components/pwa-install-button-wrapper";

// Import the PWA install handler script (will be executed on client-side only due to 'use client' directive)
import '../lib/pwa-install-handler';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: '/manifest.json'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >        {children}
        <div className="fixed bottom-6 right-6 z-50">
          <PwaInstallButtonWrapper />
        </div>
        <link rel="manifest" href="/manifest.json" />
        <Toaster/>
      </body>
    </html>
  );
}
