"""updated entire schema

Revision ID: 0d2782731052
Revises: 9839f5ecf7c8
Create Date: 2025-06-13 23:20:38.397049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d2782731052'
down_revision: Union[str, None] = '9839f5ecf7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('disease_prevented', sa.String(length=200), nullable=False),
    sa.Column('recommended_age_days', sa.Integer(), nullable=False),
    sa.Column('total_doses', sa.Integer(), nullable=False),
    sa.Column('dose_interval_days', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccine_name')
    )
    op.create_table('doctor_patient_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('first_interaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doctor_id', name='unique_doctor_patient')
    )
    op.create_table('vaccination_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_template_id', sa.UUID(), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('administered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_administered', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_details.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccine_template_id'], ['vaccine_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vaccine_template_id', 'dose_number', name='unique_user_vaccine_dose')
    )
    op.add_column('doctor_details', sa.Column('medical_council_registration_url', sa.String(length=500), nullable=True))
    op.drop_column('doctor_details', 'medical_license_number')
    op.drop_column('doctor_details', 'medical_council_registration')
    op.drop_column('doctor_details', 'license_photo_url')
    op.add_column('user_profiles', sa.Column('baby_name', sa.String(length=100), nullable=False))
    op.add_column('user_profiles', sa.Column('baby_date_of_birth', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_profiles', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user_profiles', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('user_profiles', sa.Column('parent_name', sa.String(length=100), nullable=False))
    op.add_column('user_profiles', sa.Column('parent_mobile', sa.String(length=20), nullable=False))
    op.add_column('user_profiles', sa.Column('parent_email', sa.String(length=255), nullable=False))
    op.add_column('user_profiles', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('user_profiles', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('user_profiles', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('user_profiles', sa.Column('pin_code', sa.String(length=10), nullable=False))
    op.drop_index('ix_user_profiles_username', table_name='user_profiles')
    op.drop_column('user_profiles', 'username')
    op.drop_column('user_profiles', 'timezone')
    op.drop_column('user_profiles', 'language')
    op.drop_column('user_profiles', 'first_name')
    op.drop_column('user_profiles', 'preferences')
    op.drop_column('user_profiles', 'date_of_birth')
    op.drop_column('user_profiles', 'bio')
    op.drop_column('user_profiles', 'display_name')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('vaccination_drives', 'estimated_capacity')
    op.drop_column('vaccination_drives', 'target_population')
    op.drop_column('vaccination_drives', 'location_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_drives', sa.Column('location_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vaccination_drives', sa.Column('target_population', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('vaccination_drives', sa.Column('estimated_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('date_of_birth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_user_profiles_username', 'user_profiles', ['username'], unique=False)
    op.drop_column('user_profiles', 'pin_code')
    op.drop_column('user_profiles', 'state')
    op.drop_column('user_profiles', 'city')
    op.drop_column('user_profiles', 'address')
    op.drop_column('user_profiles', 'parent_email')
    op.drop_column('user_profiles', 'parent_mobile')
    op.drop_column('user_profiles', 'parent_name')
    op.drop_column('user_profiles', 'blood_group')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('user_profiles', 'baby_date_of_birth')
    op.drop_column('user_profiles', 'baby_name')
    op.add_column('doctor_details', sa.Column('license_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('doctor_details', sa.Column('medical_council_registration', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('doctor_details', sa.Column('medical_license_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('doctor_details', 'medical_council_registration_url')
    op.drop_table('vaccination_records')
    op.drop_table('doctor_patient_relationships')
    op.drop_table('vaccine_templates')
    # ### end Alembic commands ###
