"""add vaccination reminders table

Revision ID: 0e01adbc15a3
Revises: f114f3ef952f
Create Date: 2025-06-14 21:24:17.501998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e01adbc15a3'
down_revision: Union[str, None] = 'f114f3ef952f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccination_record_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_type', sa.Enum('THIRTY_DAYS', 'FIFTEEN_DAYS', 'SEVEN_DAYS', 'ONE_DAY', name='remindertype'), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccination_record_id'], ['vaccination_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccination_record_id', 'reminder_type', name='unique_vaccination_reminder')
    )
    op.create_index('idx_vaccination_reminders_due_date', 'vaccination_reminders', ['due_date'], unique=False)
    op.create_index('idx_vaccination_reminders_user_type', 'vaccination_reminders', ['user_id', 'reminder_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vaccination_reminders_user_type', table_name='vaccination_reminders')
    op.drop_index('idx_vaccination_reminders_due_date', table_name='vaccination_reminders')
    op.drop_table('vaccination_reminders')
    # ### end Alembic commands ###
