"""change acc type

Revision ID: 12b167021280
Revises: a871412356a0
Create Date: 2025-06-13 17:24:15.269863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b167021280'
down_revision: Union[str, None] = 'a871412356a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('USER', 'ADMIN', 'WORKER', 'DOCTOR', name='accounttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"), # Adjusted to match existing_type if it was VARCHAR
               postgresql_using='account_type::accounttype'  # Added USING clause
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'account_type',
               existing_type=sa.Enum('USER', 'ADMIN', 'WORKER', 'DOCTOR', name='accounttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               # When downgrading to VARCHAR, the server default should also be VARCHAR
               existing_server_default=sa.text("'USER'::character varying"),
               postgresql_using='account_type::character varying' # Cast enum to varchar
    )
    # ### end Alembic commands ###
