"""worker and doc and vacc tables

Revision ID: 69a4867050a7
Revises: 001_add_account_type
Create Date: 2025-06-13 17:12:43.501536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a4867050a7'
down_revision: Union[str, None] = '001_add_account_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medical_license_number', sa.String(length=100), nullable=False),
    sa.Column('medical_council_registration', sa.String(length=100), nullable=True),
    sa.Column('license_photo_url', sa.String(length=500), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('hospital_affiliation', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vaccination_drives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccination_name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vaccination_city', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_details', sa.Text(), nullable=True),
    sa.Column('target_population', sa.String(length=200), nullable=True),
    sa.Column('estimated_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_drives_vaccination_city'), 'vaccination_drives', ['vaccination_city'], unique=False)
    op.create_table('worker_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('government_id', sa.String(length=100), nullable=True),
    sa.Column('certificate_photo_url', sa.String(length=500), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_worker_details_city_name'), 'worker_details', ['city_name'], unique=False)
    op.create_table('drive_worker_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['vaccination_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'worker_id', name='unique_drive_worker_assignment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drive_worker_assignments')
    op.drop_index(op.f('ix_worker_details_city_name'), table_name='worker_details')
    op.drop_table('worker_details')
    op.drop_index(op.f('ix_vaccination_drives_vaccination_city'), table_name='vaccination_drives')
    op.drop_table('vaccination_drives')
    op.drop_table('doctor_details')
    # ### end Alembic commands ###
