"""add_drive_participants_table

Revision ID: 713bc3098a14
Revises: b12323f7a962
Create Date: 2025-06-14 00:09:44.982209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713bc3098a14'
down_revision: Union[str, None] = 'b12323f7a962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccination_drive_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=False),
    sa.Column('vaccination_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('baby_name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=False),
    sa.Column('parent_mobile', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccination_drive_id'], ['vaccination_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_details.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccination_drive_id', 'user_id', name='unique_drive_user_participant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drive_participants')
    # ### end Alembic commands ###
