"""add fields

Revision ID: 84037ec9f9b4
Revises: fcf4967659db
Create Date: 2025-06-14 00:58:21.571638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84037ec9f9b4'
down_revision: Union[str, None] = 'fcf4967659db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('user_profiles', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('user_profiles', 'baby_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_profiles', 'baby_date_of_birth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_profiles', 'parent_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_profiles', 'parent_mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_profiles', 'parent_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profiles', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_profiles', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_profiles', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_profiles', 'pin_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'pin_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user_profiles', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_profiles', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_profiles', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_profiles', 'parent_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profiles', 'parent_mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_profiles', 'parent_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_profiles', 'baby_date_of_birth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user_profiles', 'baby_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user_profiles', 'preferences')
    op.drop_column('user_profiles', 'language')
    op.drop_column('user_profiles', 'timezone')
    op.drop_column('user_profiles', 'date_of_birth')
    op.drop_column('user_profiles', 'bio')
    op.drop_column('user_profiles', 'display_name')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    # ### end Alembic commands ###
