"""updated workers schema

Revision ID: 9839f5ecf7c8
Revises: f6fc4268e328
Create Date: 2025-06-13 21:37:09.524213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9839f5ecf7c8'
down_revision: Union[str, None] = 'f6fc4268e328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_details', sa.Column('government_id_url', sa.String(length=500), nullable=True))
    op.drop_column('worker_details', 'certificate_number')
    op.drop_column('worker_details', 'government_id')
    op.drop_column('worker_details', 'certificate_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_details', sa.Column('certificate_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('worker_details', sa.Column('government_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('worker_details', sa.Column('certificate_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('worker_details', 'government_id_url')
    # ### end Alembic commands ###
