"""change acc type

Revision ID: a871412356a0
Revises: 69a4867050a7
Create Date: 2025-06-13 17:18:46.382082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a871412356a0'
down_revision: Union[str, None] = '69a4867050a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'account_type',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'WORKER', 'DOCTOR', name='accounttype'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::accounttype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'account_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('USER', 'ADMIN', 'WORKER', 'DOCTOR', name='accounttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::accounttype"))
    # ### end Alembic commands ###
