"""add_account_type_column

Revision ID: dc9c7bab2dc5
Revises: a67514407e8a
Create Date: 2025-06-13 19:54:07.062165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9c7bab2dc5'
down_revision: Union[str, None] = 'a67514407e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('account_type', sa.Enum('USER', 'ADMIN', 'WORKER', 'DOCTOR', name='accounttype'), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'account_type')
    # ### end Alembic commands ###
