"""make_drive_participant_fields_optional

Revision ID: f114f3ef952f
Revises: 84037ec9f9b4
Create Date: 2025-06-14 02:06:08.279362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f114f3ef952f'
down_revision: Union[str, None] = '84037ec9f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drive_participants', 'baby_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('drive_participants', 'parent_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('drive_participants', 'parent_mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('drive_participants', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drive_participants', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('drive_participants', 'parent_mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('drive_participants', 'parent_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('drive_participants', 'baby_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
