"""fix_relationships_and_account_type

Revision ID: f6fc4268e328
Revises: dc9c7bab2dc5
Create Date: 2025-06-13 20:52:07.567778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fc4268e328'
down_revision: Union[str, None] = 'dc9c7bab2dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
