"""add_ded username

Revision ID: fcf4967659db
Revises: 713bc3098a14
Create Date: 2025-06-14 00:52:02.712796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf4967659db'
down_revision: Union[str, None] = '713bc3098a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'user_profiles', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'username')
    # ### end Alembic commands ###
